<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>md</string>
		<string>markdown</string>
		<string>mdown</string>
		<string>markdn</string>
	</array>
	<key>injectionSelector</key>
	<string>meta.embedded_css $</string>
	<key>name</key>
	<string>Embedded CSS</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>source.css</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>meta.embedded_css.markdown</string>
	<key>uuid</key>
	<string>B0C48D24-8111-4542-9B3C-C3DA76FD0693</string>
</dict>
</plist>
