<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>md</string>
		<string>markdown</string>
		<string>mdown</string>
		<string>markdn</string>
	</array>
	<key>injectionSelector</key>
	<string>meta.embedded_shell $</string>
	<key>name</key>
	<string>Embedded Shell Script</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>source.shell</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>meta.embedded_shell.markdown</string>
	<key>uuid</key>
	<string>2fb02537-fdad-44b0-8e65-d8e019188eb9</string>
</dict>
</plist>
